site_name: QOwnNotes
site_description: QOwnNotes Documentation
site_author: qownnotes.org
site_url: https://docs.qownnotes.org
dev_addr: 0.0.0.0:8000

repo_name: 'GitHub'
repo_url: 'https://github.com/pbek/QOwnNotes'

docs_dir: 'content'

# https://squidfunk.github.io/mkdocs-material/
theme:
  name: 'material'
  custom_dir: 'theme'
  language: en
  include_sidebar: true
  favicon: assets/img/qownnotes.icon.png
  logo: assets/img/qownnotes.logo.png
  feature:
    tabs: false
  palette:
    # https://github.com/squidfunk/mkdocs-material/blob/eab7148337dc7f0e9304850b606a123da6b8d559/src/assets/stylesheets/application-palette.scss#L70-L90
    primary: 'blue-grey'
    accent: 'blue-grey'
  i18n:
    prev: 'Previous'
    next: 'Next'

copyright: "Copyright &copy; 2014-2020 Patrizio Bekerle"

google_analytics:
  - 'UA-52660882-6'
  - 'docs.qownnotes.org'

extra_css:
  - assets/styles/extra.css # Our custom styles
  - assets/styles/atom-one-light.css # HightlightJS's CSS theme

extra_javascript:
  - assets/js/hljs/highlight.pack.js # Download from https://highlightjs.org/download/ and enable YAML, TOML and Dockerfile
  - assets/js/extra.js

plugins:
  - search
  - exclude:
      glob:
        - "**/include-*.md"

# https://squidfunk.github.io/mkdocs-material/extensions/admonition/
# https://facelessuser.github.io/pymdown-extensions/
markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      use_pygments: false # hljs is used instead of pygment for TOML highlighting support
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.snippets:
      check_paths: true
#  - markdown_include.include:
#      base_path: content/includes/
#      encoding: utf-8
  - toc:
      permalink: true

# Page tree
nav:
  - 'Welcome': 'index.md'
  - 'Getting Started':
      - 'Install QOwnNotes': 'getting-started/install-qownnotes.md'
  - 'Editor':
      - 'Spellchecking': 'editor/spellchecking.md'
  - 'Scripting':
      - 'Scripting': 'scripting/scripting.md'
